---
title: "Untitled"
author: "Casey McGrath"
date: "January 29, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include=FALSE}
######SEE SEASONAL_FINAL.RMD FOR DATA TO LOAD #####################################################################
#Set working directory as root directory for markdown
#this is helpful in setting where you want your outputs (like graphs) to be saved
#there are some issues but the below has worked well for me
#set directory location
mainDir <- "C:\\Users\\NeilA\\Desktop\\UH_Soil_Warming\\Data_Anaylsis"
#tell knitr what that location is
knitr::opts_knit$set(root.dir=mainDir)

#set knitr chunk options
#this is useful for global things like how images are output - images size, where saved, etc.
knitr::opts_chunk$set(#where figures are saved: in the main directory, within "Figures" folder
                      #folder will be created for you
                      fig.path=paste0(mainDir,"/Figures/"),
                      #size and alignment of images
                      #fig.height = 8, fig.width=11, fig.align='center',
                      #type of output for images: below does both pdf and png image
                      dev=c('pdf','png'),
                      #allow R code to show up in final doc but delete message and warnings
                      echo=TRUE, message=FALSE, warning=FALSE,
                      #attempts to clean up code and keep within margins (doesnt always work on long strings)
                      tidy.opts=list(width.cutoff=60), tidy=TRUE, dpi=400)
```

```{r datasets, echo =FALSE}
####################################LOAD DATA AND MANIPULATE DATAFRAMES ################################
library("dplyr")
library("tidyr")
#library("STRbook")

#set working location where files are stored
setwd("C:\\Users\\14014\\Desktop\\UH_Soil_Warming\\Data_Anaylsis\\data_wrangling")

#location IDS
locs <- read.csv(file="locations.csv", skip=1, header=FALSE, stringsAsFactors = F) 
names(locs) <- c("id", "lat", "lon", "depth")

#time file of just dates
times <- read.csv(file="times_2.csv", skip=1, header=FALSE, stringsAsFactors = F) 
names(times) <-  c("julian", "year", "month", "day")

#data for one variable at all locations and times
temp <- read.csv(file="temp_2.csv", skip=1, header=FALSE, stringsAsFactors = F) 
co2 <- read.csv(file="co2_redo_2.csv", skip=1, header=FALSE, stringsAsFactors = F) 
vwc <- read.csv(file="vwc_2.csv", skip=1, header=FALSE, stringsAsFactors = F) 

####create long dataframe#####
#Temp dataset
#set names for the variable at each location
names(temp) <- locs$id

#attach one variable to the timestamp (can do this for all other variables)
temp <- cbind(times, temp)
#check the first 10 columns
#head(names(temp), 10)

#create Tmax in long format where z is Tmax using gather
temp_long <- gather(temp, id, z, -julian, -year, -month, -day)
#look at first rows 
#head(temp_long)

#characterize ID as integer for later
temp_long$id <- as.integer(temp_long$id)

#write which proc each variable is starting with Tmax to add multiple variables under z under different proc
temp_long <- mutate(temp_long, proc = "temp")
#head(temp_long)

#repeat this process for each variable
#CO2 dataset
names(co2) <- locs$id

#attach one variable to the timestamp (can do this for all other variables)
co2 <- cbind(times, co2)
#check the first 10 columns
#head(names(co2), 10)

#create Tmax in long format where z is Tmax using gather
co2_long <- gather(co2, id, z, -julian, -year, -month, -day)
#look at first rows 
#head(co2_long)

#characterize ID as integer for later
co2_long$id <- as.integer(co2_long$id)

co2_long <- mutate(co2_long, proc = "CO2")
#head(co2_long)

#VWC dataset
names(vwc) <- locs$id

#attach one variable to the timestamp (can do this for all other variables)
vwc <- cbind(times, vwc)
#check the first 10 columns
#head(names(vwc), 10)

#create Tmax in long format where z is Tmax using gather
vwc_long <- gather(vwc, id, z, -julian, -year, -month, -day)
#look at first rows 
#head(vwc_long)

#characterize ID as integer for later
vwc_long$id <- as.integer(vwc_long$id)

vwc_long <- mutate(vwc_long, proc = "VWC")
#head(vwc_long)

#precip dataset
#names(precip) <- locs$id

#attach one variable to the timestamp (can do this for all other variables)
#precip <- cbind(times, precip)
#check the first 10 columns
#head(names(precip), 10)

#create Tmax in long format where z is Tmax using gather
#precip_long <- gather(precip, id, z, -julian, -year, -month, -day)
#look at first rows 
#head(precip_long)

#characterize ID as integer for later
#precip_long$id <- as.integer(precip_long$id)

#precip_long <- mutate(precip_long, proc = "precip")
#head(precip_long)

#construct final data frame
Lyon_df <- rbind(temp_long, co2_long, vwc_long) #, precip_long)

#create group summary for the data by year and proc
summ <- group_by(Lyon_df, month, proc) %>% # groupings
summarise(mean_proc = mean(z)) # operation

#add spatial data to dataframe
Lyon_df <- left_join(Lyon_df, locs, by = "id")

#libraries for spatio-temporal data classes 
library("sp")
library("spacetime")

#combine year month day
Lyon_df$date <- with(Lyon_df,
paste(year, month, day, sep = "-"))
#head(Lyon_df$date, 4) # show first four elements
## [1] "1990-1-1" "1990-1-2" "1990-1-3" "1990-1-4"

#create date object 
Lyon_df$date <- as.Date(Lyon_df$date)
#class(Lyon_df$date)

#dataframe with #26 in instaed of outlier
Lyon_dfco <- subset(Lyon_df, Lyon_df$proc == "CO2")
Lyon_dftemp <- subset(Lyon_df, Lyon_df$proc == "temp")
Lyon_dfvwc  <- subset(Lyon_df, Lyon_df$proc == "VWC")
#Lyon_dfprecip  <- subset(Lyon_df, Lyon_df$proc == "precip")

Lyon_final <-Lyon_dftemp

Lyon_final$temp <-Lyon_dftemp$z
Lyon_final$co2 <- Lyon_dfco$z
Lyon_final$vwc <- Lyon_dfvwc$z
#Lyon_final$precip <- Lyon_dfprecip$z

#get rid of unnesscery columns 
Lyon_final <- subset(Lyon_final, select = -c(z, proc, julian, day, month, year))

#soil charactertistics dataset for PCA
soil_char_PCA <- read.csv(file="soil_characteristics_PCAA.csv", skip=1, header=FALSE, stringsAsFactors = F) 
names(soil_char_PCA) <-  c("depth","C",	"N",	"pH_H2O",	"Delta_pH",	"non_crystal",	"Fe_h_Fe_d","Al_p","Fe_p","Al_p_Al_h",	"H_16S",	"S_16S",	"H_ITS",	"S_ITS")


#create time_df26 o be used as main dataset below
df <- aggregate(Lyon_final[,6:8], list(Lyon_final$id), mean)
df$id <- df$Group.1
soil_char_PCA$id <- c(1:50)

time_df <- left_join(soil_char_PCA, df, by = "id")
time_df26 <- subset(time_df, time_df$id != 26)

#######soil charactertistics dataset with NAs ######
soil_char <- read.csv(file="soil_characteristics_NA.csv", skip=1, header=FALSE, stringsAsFactors = F) 
names(soil_char) <-  c("depth","C",	"N",	"pH_H2O",	"Delta_pH",	"non_crystal",	"Fe_oxides",	"OM_complexed",	"H_16S",	"S_16S",	"H_ITS",	"S_ITS")

Lyon_final$co2 <- Lyon_final$co2 / 1000^2 *44.01

#create time_df26 o be used as main dataset below
df <- aggregate(Lyon_final[,6:8], list(Lyon_final$id), mean)
df$id <- df$Group.1
soil_char$id <- c(1:50)

time_df <- left_join(soil_char, df, by = "id")
time_df26 <- subset(time_df, time_df$id != 26)
```

```{r max_min}
####################IDENTIFY THE TOP 20% AND LOWEST 20% FOR THE MEAN TEMP AT EACH DEPTH##############################
library(dplyr)
#subset mean dataset for depth =20cm 
mean_20 <- subset(time_df, time_df$depth ==20)

#top two high temperature values 
max_20 <- mean_20 %>%  top_n(2, temp)
#top two low temperature values 
min_20 <-mean_20 %>%  top_n(-2, temp)

#subset mean dataset for depth =40cm 
mean_40 <- subset(time_df, time_df$depth ==40)

#top two high temperature values 
max_40 <- mean_40 %>%  top_n(2, temp)
#top two low temperature values 
min_40 <- mean_40 %>%  top_n(-2, temp)

#subset mean dataset for depth =60cm 
mean_60 <- subset(time_df, time_df$depth ==60)

#top two high temperature values 
max_60 <- mean_60 %>%  top_n(2, temp)
#top two low temperature values 
min_60 <- mean_60 %>%  top_n(-2, temp)

#subset mean dataset for depth =80cm 
mean_80 <- subset(time_df, time_df$depth ==80)

#top two high temperature values 
max_80 <-mean_80 %>%  top_n(2, temp)
#top two low temperature values 
min_80 <- mean_80 %>%  top_n(-2, temp)

#subset mean dataset for depth =20cm 
mean_100 <- subset(time_df, time_df$depth ==100)

#top two high temperature values 
max_100 <- mean_100 %>%  top_n(2, temp)
#top two low temperature values 
min_100 <- mean_100 %>%  top_n(-2, temp)


#bind top and low 20% for all depths into dataframe
max_min_df <- bind_rows(max_20, min_20,max_40, min_40,max_60, min_60, max_80, min_80, max_100, min_100)
#max_min_df <- max_min_df[c(1,5:8)]
print(max_min_df$id)
```

```{r}
library("dplyr")
Lyon_adj <- Lyon_final[c(1,4,6:8)]
Lyon_adj_mean <- aggregate(.~Lyon_adj$id, data= Lyon_adj, mean)
Lyon_adj_mean <- Lyon_adj_mean[c(2:6)]
Lyon_adj_mean <- left_join(soil_char_PCA, Lyon_adj_mean, by = "id")
Lyon_adj_mean <- Lyon_adj_mean[c(1:15,17:19)]
Lyon_adj_mean$depth <- Lyon_adj_mean$depth.x
Lyon_adj_mean$depth <- factor(Lyon_adj_mean$depth)
```

```{r}
Lyon_deltatemp <- Lyon_final[c(1,6)]
Lyon_deltatemp_mean <- aggregate(.~Lyon_deltatemp$id, data= Lyon_deltatemp, mean)
Lyon_deltatemp_mean$Delta_temp <- Lyon_deltatemp_mean$temp - 23.15 #22.06 is the average ambient soil temp
Lyon_adj_mean$Delta_temp  <- Lyon_deltatemp_mean$Delta_temp 
```

```{r}
#plot delta co2 as a response of delta temp for top 20% and lower 20% of all temperatures
###20cm deLta co2 and temp#####
Lyon_max_20 <- subset(Lyon_final, subset = id %in% c(11, 46))
Lyon_min_20 <- subset(Lyon_final, subset = id %in% c(6,31))

Lyon_max_20$delta_co2<- Lyon_max_20$co2- Lyon_min_20$co2
Lyon_max_20$delta_temp <- Lyon_max_20$temp- Lyon_min_20$temp


###40cm deLta co2 and temp#####
Lyon_max_40 <- subset(Lyon_final, subset = id %in% c(17, 22))
Lyon_min_40 <- subset(Lyon_final, subset = id %in% c(2,47))

Lyon_max_40$delta_co2<- Lyon_max_40$co2- Lyon_min_40$co2
Lyon_max_40$delta_temp <- Lyon_max_40$temp - Lyon_min_40$temp


###60cm deLta co2 and temp#####
Lyon_max_60 <- subset(Lyon_final, subset = id %in% c(3, 33))
Lyon_min_60 <- subset(Lyon_final, subset = id %in% c(8,28))

Lyon_max_60$delta_co2<- Lyon_max_60$co2- Lyon_min_60$co2
Lyon_max_60$delta_temp <- Lyon_max_60$temp - Lyon_min_60$temp

###80cm deLta co2 and temp#####
Lyon_max_80 <- subset(Lyon_final, subset = id %in% c(29, 49))
Lyon_min_80 <- subset(Lyon_final, subset = id %in% c(9,44))

Lyon_max_80$delta_co2<- Lyon_max_80$co2- Lyon_min_80$co2
Lyon_max_80$delta_temp <- Lyon_max_80$temp - Lyon_min_80$temp


###100cm deLta co2 and temp#####
Lyon_max_100 <- subset(Lyon_final, subset = id %in% c(35, 40))
Lyon_min_100 <- subset(Lyon_final, subset = id %in% c(15,30))

Lyon_max_100$delta_co2<- Lyon_max_100$co2- Lyon_min_100$co2
Lyon_max_100$delta_temp <- Lyon_max_100$temp - Lyon_min_100$temp

```

```{r}
#install.packages("viridis")  # Install
library("mgcViz")
library("dplyr")
library(RColorBrewer)
library(colortools)

#create dataframe of all depths delta temp and delta co2 
DF_delta <- bind_rows(Lyon_max_80,Lyon_max_60,Lyon_max_40,Lyon_max_20, Lyon_max_100)
#https://otexts.com/fpp2/regression.html
DF_delta$depth <- factor(DF_delta$depth)
#plot delta temp vs. delta co2 produced for all depths
p <- ggplot(DF_delta, aes(x=delta_temp, y=delta_co2, col=depth)) +
    geom_point(aes(shape=depth), size =2.2)+
    scale_color_manual(
                      name = "Depth (cm)",
                      labels = c("20", "40", "60", "80", "100"),
                     #values =  c( "#F8766D",  "#A3A500", "#00BF7D","#00B0F6", "#E76BF3")) +   
                     values = c("grey70", "grey60","grey50","grey30","grey10"))+
    scale_shape_manual(name = "Depth (cm)",
                     labels = c("20", "40", "60", "80", "100"),
                     values = c(16,4,18,15,17))+
    geom_hline(yintercept = 0, linetype = "solid", color = "black", size =1)+ #line at zero
    geom_vline(xintercept = 4, linetype = "dashed", color = "red", size =1)+ #line at 4 degrees
      
    labs(
      x = expression(Delta ~ "Soil temperature (°C)"),
      y = expression(Delta ~'CO'[2 ]~ 'produced ('~ g~ m^-3 ~ hr^-1~')'))

p + theme_classic(base_size = 14) +theme(legend.position = "top") 

```


```{r}
Lyon_adj_mean$non_crystal <- Lyon_adj_mean$non_crystal
Lyon_adj_mean$Fe_h_Fe_d <- Lyon_adj_mean$Fe_oxides
Lyon_adj_mean$Al_p <- Lyon_adj_mean$OM_complexed_Al
Lyon_adj_mean$Fe_p <- Lyon_adj_mean$OM_complexed_Fe
```

```{r}
#https://www.marktechpost.com/2019/04/30/principal-component-analysis-pca-using-r/
df <- Lyon_adj_mean[,c(2:9,12,14,17,18,20)]

# 1. Correlation matrix
df.scaled <- scale(df, center = TRUE, scale = TRUE)
res.cor <- cor(df.scaled)
round(res.cor, 2)

# 2. Calculate eigenvectors/eigenvalues
res.eig <- eigen(res.cor)
res.eig

# Transpose eigeinvectors
eigenvectors.t <- t(res.eig$vectors)
# Transpose the adjusted data
df.scaled.t <- t(df.scaled)
# The new dataset
df.new <- eigenvectors.t %*% df.scaled.t
# Transpose new data ad rename columns
df.new <- t(df.new)
colnames(df.new) <- c("PC1", "PC2", "PC3", "PC4", "PC5", "PC6", "PC7", "PC8", "PC9", "PC10", "PC11", "PC12","PC13" )
head(df.new)
```

```{r}
options(digits=3) #just so we don't get so many digits in our results
dat <- Lyon_adj_mean[,c(2:9,12,14,17,18,20)]
p<-ncol(dat)#no of variables
R<-cor(dat)#saving the correlation matrix

e<-eigen(R) #solving for the eigenvalues and eigenvectors from the correlation matrix

L<-e$values #placing the eigenvalues in L
Vm<-matrix(0,nrow=p,ncol=p) #creating a p x p matrix with zeroes.
#Vm is an orthogonal matrix since all correlations between variable are 0.
diag(Vm)<-L #putting the eigenvalues in the diagonals

comp.matrix<-e$vectors %*% sqrt(Vm) #sometimes referred to as P matrix
#or eigenvectors x sqrt(Vm): P %*% t(P) is equal to the R matrix.
comp.matrix

library(psych)
pca<-principal(dat,nfactor=p,rotate="none") #forcing to extract p=6 components
pca

loadings<-e$vectors %*% sqrt(Vm) #these are the correlations as we have shown earlier
loadings #signs are just different

L/p
```


```{r}
library(factoextra)
library(RColorBrewer)
res.pca <- prcomp(dat, scale = TRUE, center = TRUE)
#fviz_pca_ind(res.pca,
             # col.ind = "cos2", # Color by the quality of representation
             # gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             # repel = TRUE     # Avoid text overlapping
             # )

p <- fviz_pca_biplot(res.pca, axes = c(1, 2), repel = TRUE,


                habillage = Lyon_adj_mean$depth,  # Individuals color
                label = "var", 
                addEllipses=TRUE,
                #invisible = "var",
              #  palette = c("grey80", "grey60","grey40","grey20","grey10"),
                pointsize = 2,                                              
            
col.var = "black", # Variables color 
               ggtheme = theme_classic(base_size = 18), title = "")

p          +theme(legend.position = "top") 

```

```{r}
library(mgcv)
library(mgcViz)

Lyon_adj_mean$depth <- as.numeric(as.character(Lyon_adj_mean$depth))

#model without allophane ratio (better fit)
M_Global = gam(log(co2) ~ s(vwc,k=4) + s(Delta_temp, k=4) + s(C, k=4) + s(N, k=4) + s(pH_H2O, k =4)+ s(Delta_pH, k=4) + s(non_crystal, k =4) + s(Fe_h_Fe_d,k=4) + s(Al_p, k=4) + s(Fe_p, k=4) + s(S_16S,k=4) + s(S_ITS, k=4) + s(depth, k =4)+ s(id, bs = "re")+ 1, data = Lyon_adj_mean, na.action = "na.fail", method ="REML")

#model without allophane ratio (better fit)
M_Global_31 = gam(log(co2) ~ s(vwc,k=4) + s(Delta_temp, k=4) + s(C, k=4) + s(N, k=4) + s(pH_H2O, k =4)+ s(Delta_pH, k=4) + s(non_crystal, k =4) + s(Fe_h_Fe_d,k=4) + s(Al_p, k=4) + s(Fe_p, k=4) + s(S_16S,k=4) + s(S_ITS, k=4) + s(depth, k =4), data = Lyon_adj_mean, na.action = "na.fail", method ="REML")

#with depth as a factor not continuous 
Lyon_adj_mean$depth <- factor(Lyon_adj_mean$depth)
M_Global_3 = gam(log(co2) ~ s(vwc,k=4) + s(Delta_temp, k=4) + s(C, k=4) + s(N, k=4) + s(pH_H2O, k =4)+ s(Delta_pH, k=4) + s(non_crystal, k =4) + s(Fe_h_Fe_d,k=4) + s(Al_p, k=4) + s(Fe_p, k=4) + s(S_16S,k=4) + s(S_ITS, k=4) + depth + s(id, bs = "re")+ 1, data = Lyon_adj_mean, na.action = "na.fail", method ="REML")

#model without allophane ratio (better fit)
M_Global_13 = gam(log(co2) ~ s(vwc,k=4) + s(Delta_temp, k=4) + s(C, k=4) + s(N, k=4) + s(pH_H2O, k =4)+ s(Delta_pH, k=4) + s(non_crystal, k =4) + s(Fe_h_Fe_d,k=4) + s(Al_p, k=4) + s(Fe_p, k=4) + s(S_16S,k=4) + s(S_ITS, k=4) + depth, data = Lyon_adj_mean, na.action = "na.fail", method ="REML")


summary(M_Global)
layout(matrix(1:4,ncol=2,byrow = T))
gam.check(M_Global)
b <- getViz(M_Global)

check(b,
     a.qq = list(method = "tnorm", 
     a.cipoly = list(fill = "light blue")), 
     a.respoi = list(size = 0.5), 
     a.hist = list(bins = 10))

print(plot(b, allTerms = T), pages = 1)

AIC(M_Global, M_Global_3, M_Global_13, M_Global_31)
```

```{r}
library(MuMIn)
dd <- dredge(M_Global)
d <-subset(dd, delta < 2)

# Visualize the model selection table:
par(mar = c(3,5,6,4))
plot(d, labAsExpr = TRUE)

# Model average models with delta AICc < 4
model.avg(dd, subset = delta < 2)

#'Best' model
summary(get.models(dd, 1)[[1]])

#2nd 'Best' model
summary(get.models(dd, 2)[[1]])
```

```{r}
#https://stat.ethz.ch/pipermail/r-help/2011-February/269005.html
#The partial residuals for a smooth term are just the whole model residuals + 
#the corresponding estimate of the smooth term. You can use predict to access 
#the latter and compute them quite easily. For example...

  #set.seed(0) ## simulate some data...
     #dat <- gamSim(1,n=400,dist="normal",scale=2)
     ## fit a model...
   #  b <- gam(y~s(x0)+s(x1)+s(x2)+s(x3),data=dat)
     fv <- predict(M_Global,type="terms") ## get term estimates
     ## compute partial residuals for first smooth...          
     prsd1 <- residuals(M_Global,type="working") + fv[,1] #VWC
     prsd8 <- residuals(M_Global,type="working") + fv[,8] #Fe
     plot(M_Global,select=1) ## plot first smooth
     ## add random selection of partial residuals
     ind <- sample(1:length(prsd1),50)
     points(Lyon_adj_mean$vwc[ind],prsd1[ind],pch=19, cex =1, col="pink")
```

```{r}
limits <- range(Lyon_adj_mean$co2)
log_limits <- range(log(Lyon_adj_mean$co2))
```

```{r}
library(ggplot2)
Lyon_adj_mean$depth <- as.numeric(as.character(Lyon_adj_mean$depth))
dt <- ggplot(Lyon_adj_mean, aes(x = Delta_temp, y = co2,colour = depth)) + 
   geom_point()+
  #geom_text(aes(label=id),hjust=0, vjust=0, size = 3)+
  scale_color_gradient(low="tan", high="blue", name = "Depth (cm)")+
  geom_point(colour = "white", size =4) +
  geom_point(size = 2)+
  #scale_colour_manual(name="Depth (cm)", values= c("red", "orange", "violet","light blue", "dark blue")) + 
    labs(
      x = expression(Delta~ 'soil temperature (°C)'),
      y = expression('CO'[2 ]~ 'produced ('~ g~ m^-3 ~ hr^-1~')'),
      ylim(limits))
 # scale_shape_discrete(name  ="Depth(cm)")+ theme_gray(base_size = 12)


dt2 <- dt + stat_smooth(method = "gam", formula = y~ s(x, k = 4), size = 1, se = TRUE, colour = "black") +     theme_classic()   +     theme(plot.margin = unit(c(0,0,0,0), "cm"),
            plot.background = element_blank(),

 legend.position = "none") +coord_cartesian(ylim = limits)
```

```{r}
dph <- ggplot(Lyon_adj_mean, aes(x = Delta_pH, y = co2,colour = depth)) + 
   geom_point()+
  #geom_text(aes(label=id),hjust=0, vjust=0, size = 3)+
  scale_color_gradient(low="tan", high="blue", name = "Depth (cm)")+
  geom_point(colour = "white", size =4) +
  geom_point(size = 2)+
  #scale_colour_manual(name="Depth (cm)", values= c("red", "orange", "violet","light blue", "dark blue")) + 
    labs(
      x = expression(Delta~ 'pH'),
      y = expression('CO'[2 ]~ 'produced ('~ g~ m^-3 ~ hr^-1~')') )
#  scale_shape_discrete(name  ="Depth(cm)")+ theme_gray(base_size = 12)


dph2 <- dph + stat_smooth(method = "gam", formula = y~ s(x, k = 4), size = 1, se = TRUE, colour = "black") + theme_classic()    +  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
            plot.margin = unit(c(0,0,0,0), "cm"),
            plot.background = element_blank(),
legend.position = "none")+coord_cartesian(ylim = limits)
```

```{r}
non <- ggplot(Lyon_adj_mean, aes(x = non_crystal/1000, y = log(co2),colour = depth)) + 
   geom_point()+
  #geom_text(aes(label=id),hjust=0, vjust=0, size = 3)+
  scale_color_gradient(low="tan", high="blue", name = "Depth (cm)")+
  geom_point(colour = "white", size =4) +
  geom_point(size = 2)+
  #scale_colour_manual(name="Depth (cm)", values= c("red", "orange", "violet","light blue", "dark blue")) + 
    labs(
      x = expression('P-NCM conc. ( '~ g ~ kg^-1 ~'soil)'),
      y = expression('CO'[2 ]~ 'produced ('~ g~ m^-3 ~ hr^-1~')') ,
      ylim(log_limits))
#  scale_shape_discrete(name  ="Depth(cm)")+ theme_gray(base_size = 12)


non2 <- non + stat_smooth(method = "gam", formula = y~ s(x, k = 4), size = 1, se = TRUE, colour = "black") + theme_classic()   +  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
            plot.margin = unit(c(0,0,0,0), "cm"),
            plot.background = element_blank(),
 legend.position = "none")      +coord_cartesian(ylim = log_limits)                                                                                                           
```

```{r}
f <- ggplot(Lyon_adj_mean, aes(x = Fe_h_Fe_d, y = co2,colour = depth)) + 
   geom_point()+
  #geom_text(aes(label=id),hjust=0, vjust=0, size = 3)+
  scale_color_gradient(low="tan", high="blue", name = "Depth (cm)")+
  geom_point(colour = "white", size =4) +
  geom_point(size = 2)+
  #scale_colour_manual(name="Depth (cm)", values= c("red", "orange", "violet","light blue", "dark blue")) + 
    labs(
      x = expression('Active Fe ratio'),
      y = expression('CO'[2 ]~ 'produced ('~ g~ m^-3 ~ hr^-1~')') )
#  scale_shape_discrete(name  ="Depth(cm)")+ theme_gray(base_size = 12)


f2 <- f + stat_smooth(method = "gam", formula = y~ s(x, k = 4), size = 1, se = TRUE, colour = "black") + theme_classic()    +       theme(plot.margin = unit(c(0,0,0,0), "cm"),
            plot.background = element_blank(),
  legend.position = "none")     +coord_cartesian(ylim = limits)                                                                                                           
```

```{r}
c <- ggplot(Lyon_adj_mean, aes(x = C, y = co2,colour = depth)) + 
   geom_point()+
  #geom_text(aes(label=id),hjust=0, vjust=0, size = 3)+
  scale_color_gradient(low="tan", high="blue", name = "Depth (cm)")+
  geom_point(colour = "white", size =4) +
  geom_point(size = 2)+
  #scale_colour_manual(name="Depth (cm)", values= c("red", "orange", "violet","light blue", "dark blue")) + 
    labs(
      x = expression('C (%)'),
      y = expression('CO'[2 ]~ 'produced ('~ g~ m^-3 ~ hr^-1~')') )
#  scale_shape_discrete(name  ="Depth(cm)")+ theme_gray(base_size = 12)


c2 <- c + stat_smooth(method = "gam", formula = y~ s(x, k = 4), size = 1, se = TRUE, colour = "black") + theme_classic()      +       theme(plot.margin = unit(c(0,0,0,0), "cm"),
            plot.background = element_blank(),
 legend.position = "none")  +coord_cartesian(ylim = limits)                                                                                                        
```

```{r}
al <- ggplot(Lyon_adj_mean, aes(x = Al_p/1000, y = co2,colour = depth)) + 
   geom_point()+
  #geom_text(aes(label=id),hjust=0, vjust=0, size = 3)+
  scale_color_gradient(low="tan", high="blue", name = "Depth (cm)")+
  geom_point(colour = "white", size =4) +
  geom_point(size = 2)+
  #scale_colour_manual(name="Depth (cm)", values= c("red", "orange", "violet","light blue", "dark blue")) + 
    labs(
      x = expression('OM Complexed Al( '~ g ~ kg^-1 ~'soil)'),
      y = expression('CO'[2 ]~ 'produced ('~ g~ m^-3 ~ hr^-1~')') )
#  scale_shape_discrete(name  ="Depth(cm)")+ theme_gray(base_size = 12)


al2 <- al + stat_smooth(method = "gam", formula = y~ s(x, k = 4), size = 1, se = TRUE, colour = "black") + theme_classic()        +  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
            plot.margin = unit(c(0,0,0,0), "cm"),
            plot.background = element_blank(),
 legend.position = "none")  +coord_cartesian(ylim = limits)                                                                                                        
```

```{r}
fe <- ggplot(Lyon_adj_mean, aes(x = Fe_p/1000, y = co2,colour = depth)) + 
   geom_point()+
  #geom_text(aes(label=id),hjust=0, vjust=0, size = 3)+
  scale_color_gradient(low="tan", high="blue", name = "Depth (cm)")+
  geom_point(colour = "white", size =4) +
  geom_point(size = 2)+
  #scale_colour_manual(name="Depth (cm)", values= c("red", "orange", "violet","light blue", "dark blue")) + 
    labs(
      x = expression('OM Complexed Fe( '~ g ~ kg^-1 ~'soil)'),
      y = expression('CO'[2 ]~ 'produced ('~ g~ m^-3 ~ hr^-1~')') )
#  scale_shape_discrete(name  ="Depth(cm)")+ theme_gray(base_size = 12)


fe2 <- fe + stat_smooth(method = "gam", formula = y~ s(x, k = 4), size = 1, se = TRUE, colour = "black") + theme_classic()      +   theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
            plot.margin = unit(c(0,0,0,0), "cm"),
            plot.background = element_blank(),
 legend.position = "none")  +coord_cartesian(ylim = limits)                                                                                                        
```

```{r}
n <- ggplot(Lyon_adj_mean, aes(x = N, y = co2,colour = depth)) + 
   geom_point()+
  #geom_text(aes(label=id),hjust=0, vjust=0, size = 3)+
  scale_color_gradient(low="tan", high="blue", name = "Depth (cm)")+
  geom_point(colour = "white", size =5) +
  geom_point(size = 3)+
  #scale_colour_manual(name="Depth (cm)", values= c("red", "orange", "violet","light blue", "dark blue")) + 
    labs(
      x = expression('N (%)'),
      y = expression('CO'[2 ]~ 'produced ('~ g~ m^-3 ~ hr^-1~')') )
#  scale_shape_discrete(name  ="Depth(cm)")+ theme_gray(base_size = 12)


n2 <- n + stat_smooth(method = "gam", formula = y~ s(x, k = 4), size = 1, se = TRUE, colour = "black") + theme_classic()     +  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
            plot.margin = unit(c(0,0,0,0), "cm"),
            plot.background = element_blank(),
 legend.position = "none")  +coord_cartesian(ylim = limits)                                                                                                        
```

```{r}
ph <- ggplot(Lyon_adj_mean, aes(x = pH_H2O, y = co2,colour = depth)) + 
   geom_point()+
  #geom_text(aes(label=id),hjust=0, vjust=0, size = 3)+
  scale_color_gradient(low="tan", high="blue", name = "Depth (cm)")+
  geom_point(colour = "white", size =5) +
  geom_point(size = 3)+
  #scale_colour_manual(name="Depth (cm)", values= c("red", "orange", "violet","light blue", "dark blue")) + 
    labs(
      x = expression('pH'),
      y = expression('CO'[2 ]~ 'produced ('~ g~ m^-3 ~ hr^-1~')') )
#  scale_shape_discrete(name  ="Depth(cm)")+ theme_gray(base_size = 12)


ph2 <- ph + stat_smooth(method = "gam", formula = y~ s(x, k = 4), size = 1, se = TRUE, colour = "black") + theme_classic()       +   theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
            plot.margin = unit(c(0,0,0,0), "cm"),
            plot.background = element_blank(),
 legend.position = "none")  +coord_cartesian(ylim = limits)                                                                                                        
```

```{r}
bac <- ggplot(Lyon_adj_mean, aes(x = S_16S, y = co2,colour = depth)) + 
   geom_point()+
  #geom_text(aes(label=id),hjust=0, vjust=0, size = 3)+
  scale_color_gradient(low="tan", high="blue", name = "Depth (cm)")+
  geom_point(colour = "white", size =5) +
  geom_point(size = 3)+
  #scale_colour_manual(name="Depth (cm)", values= c("red", "orange", "violet","light blue", "dark blue")) + 
    labs(
      x = expression('16S richness'),
      y = expression('CO'[2 ]~ 'produced ('~ g~ m^-3 ~ hr^-1~')') )
#  scale_shape_discrete(name  ="Depth(cm)")+ theme_gray(base_size = 12)


bac2 <- bac + stat_smooth(method = "gam", formula = y~ s(x, k = 4), size = 1, se = TRUE, colour = "black") + theme_classic()     +  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
            plot.margin = unit(c(0,0,0,0), "cm"),
            plot.background = element_blank(),
 legend.position = "none")  +coord_cartesian(ylim = limits)                                                                                                        
```

```{r}
vwc <- ggplot(Lyon_adj_mean, aes(x = vwc*100, y = co2,colour = depth)) + 
   geom_point()+
  #geom_text(aes(label=id),hjust=0, vjust=0, size = 3)+
  scale_color_gradient(low="tan", high="blue", name = "Depth (cm)")+
  geom_point(colour = "white", size =4) +
  geom_point(size = 2)+
  #scale_colour_manual(name="Depth (cm)", values= c("red", "orange", "violet","light blue", "dark blue")) + 
    labs(
      x = expression('Volumetric water content'),
      y = expression('CO'[2 ]~ 'produced ('~ g~ m^-3 ~ hr^-1~')') )
#  scale_shape_discrete(name  ="Depth(cm)")+ theme_gray(base_size = 12)


vwc2 <- vwc + stat_smooth(method = "gam", formula = y~ s(x, k = 4), size = 1, se = TRUE, colour = "black") + theme_classic()     +  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
            plot.margin = unit(c(0,0,0,0), "cm"),
            plot.background = element_blank(),
 legend.position = "none")  +coord_cartesian(ylim = limits)                                                                                                        
```


```{r}
library(PtProcess)
library(ggplot2)
library(gridExtra)
library(cowplot)


pj <- plot_grid(dt2, vwc2, dph2, bac2, f2, non2, al2, fe2,  c2, n2, ph2, align = "hv")
```

```{r}
#https://datascienceplus.com/multicollinearity-in-r/
myvars <- names(Lyon_adj_mean) %in% c("C", "N", "Al_p", "Fe_p", "Fe_h_Fe_d", "pH_H2O", "S_16S","vwc", "non_crystal", "Delta_pH", "Delta_temp", "co2")

dredge_data <- Lyon_adj_mean[myvars]
res <- cor(dredge_data, method = "pearson", use = "complete.obs")

library(corrplot)
corrplot(res, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45)

library(mctest)
omcdiag(dredge_data, dredge_data$co2)

library(mctest)
imcdiag(dredge_data, dredge_data$co2)

library(ppcor)
pcor(dredge_data, method = "pearson")
```



```{r}
library(mgcv)
concurvity(M_Global,full=TRUE)
```

```{r}
Lyon_adj_mean$depth <- factor(Lyon_adj_mean$depth)
library(mgcv)
library(mgcViz)
library(MuMIn)

O1 =  gam(log(co2) ~ s(Delta_temp, k =3, by =depth)+ s(S_16S, k=3, by =depth)+ s(vwc, k=3, by =depth)  + s(non_crystal, k=3, by =depth)  + s(id, bs = "re")+ 1, data = Lyon_adj_mean, na.action = "na.fail", method ="REML")

O2 =  gam(log(co2) ~ s(Delta_temp, k=3, by =depth) +s(S_16S, k =3, by =depth)+ s(vwc, k=3, by =depth)  +  s(Fe_h_Fe_d, k=3, by =depth) + s(id, bs = "re")+ 1, data = Lyon_adj_mean, na.action = "na.fail", method ="REML")

O3 =  gam(log(co2) ~ s(Delta_temp, k =3, by =depth)+ s(S_16S, k=3, by =depth)+ s(N, k=3, by =depth)  + s(non_crystal, k=3, by =depth)  + s(id, bs = "re")+ 1, data = Lyon_adj_mean, na.action = "na.fail", method ="REML")

O4 =  gam(log(co2) ~ s(Delta_temp, k=3, by =depth) +s(C, k =3, by =depth)+ s(vwc, k=3, by =depth)  +  s(Fe_h_Fe_d, k=3, by =depth) + s(id, bs = "re")+ 1, data = Lyon_adj_mean, na.action = "na.fail", method ="REML")

O5 =  gam(log(co2) ~ s(Delta_temp, k=3, by =depth) +s(S_16S, k =3, by =depth)+ s(vwc, k=3, by =depth)  +  s(Delta_pH, k=3, by =depth) + s(id, bs = "re")+ 1, data = Lyon_adj_mean, na.action = "na.fail", method ="REML")

AICc(O1, O2, O3, O4, O5)
     # ,O2,O3, O4,O5, O6,O7, O8, O9, O10, O11)
```


```{r}
# plot the smooth predictor function for x1 with ggplot to get a nicer looking graph
p <- predict(O1, type="lpmatrix")
beta <- coef(O1)[grepl("C", names(coef(O1)))]
s <- p[,grepl("C", colnames(p))] %*% beta
ggplot(data=cbind.data.frame(s, Lyon_adj_mean$C), aes(x=Lyon_adj_mean$C, y=s)) + geom_line()
```

```{r}
summary(O1)
layout(matrix(1:4,ncol=2,byrow = T))
gam.check(O1)
b <- getViz(O1)

check(b,
     a.qq = list(method = "tnorm", 
     a.cipoly = list(fill = "light blue")), 
     a.respoi = list(size = 0.5), 
     a.hist = list(bins = 10))

print(plot(b, allTerms = T), pages = 1)
```

```{r}
#https://stat.ethz.ch/pipermail/r-help/2011-February/269005.html
#The partial residuals for a smooth term are just the whole model residuals + 
#the corresponding estimate of the smooth term. You can use predict to access 
#the latter and compute them quite easily. For example...

  #set.seed(0) ## simulate some data...
     #dat <- gamSim(1,n=400,dist="normal",scale=2)
     ## fit a model...
   #  b <- gam(y~s(x0)+s(x1)+s(x2)+s(x3),data=dat)
     fv <- predict(O1,type="terms") ## get term estimates
     ## compute partial residuals for first smooth...          
     prsd1 <- residuals(O1,type="working") + fv[,1] #VWC
     prsd8 <- residuals(O1,type="working") + fv[,4] #Fe
     plot(O1,select=1) ## plot first smooth
     ## add random selection of partial residuals
     ind <- sample(1:length(prsd8),50)
     points(Lyon_adj_mean$non_crystal[ind],prsd1[ind],pch=19, cex =1, col="pink")
```

```{r}
library(RColorBrewer)
bp <- ggplot(Lyon_adj_mean, aes(x=non_crystal/1000, y=co2)) +
  geom_point(aes(color= as.factor(depth)), show.legend = TRUE) + 
  geom_smooth(method = "gam",formula = y~ s(x, k = 4), se=FALSE, fullrange=FALSE, aes(color= as.factor(depth)))+
     labs(
      x = expression('Non crystalline conc. ( '~ g ~ kg^-1 ~'soil)'),
      y = expression('Log transformed CO'[2 ]~ 'produced ('~ mu ~ mol~ m^-3 ~ hr^-1~')') )+
  scale_y_continuous(trans = "log10")

bp + scale_color_brewer(palette="Greys", name= "Depth (cm)") +theme(legend.position = c(1, 1), legend.justification = c(1, 1))
```

```{r}
library(MuMIn)
library(RColorBrewer)
get.models(dd, subset = delta < 2)

imp_dd <- importance(dd)

dd_corr <- as.data.frame(imp_dd)
dd_corr$term <- c("id","vwc", "Non crystalline","N","Active Fe", "16S", "Delta temp", "C", "OM Fe", "pH", "OM Al", "ITS", "Delta pH")

p<-ggplot(data=dd_corr, aes(x=reorder(term, -imp_dd), y=imp_dd)) +
  geom_bar(stat="identity",  color='gray',fill='gray')+
  labs(
      y = expression('Sum of weights'),
      x = "Model term") 
p + theme_classic(base_size = 14)+ theme(axis.text.x = element_text(angle = 90, hjust = 1)) + scale_fill_brewer(palette="Greens")
   

```

```{r}
d <-subset(dd, delta < 2)

dp <- plot(d, 
    labels = attr(d, "terms"), labAsExpr = FALSE,
    col = c("gray"), col2 = "white", border = par("col"),,
    axes = TRUE, ann = TRUE) 
```

```{r}
library(visreg)
library(mgcViz)
visreg(O1, "Delta_temp", xlab="vari", ylab="CO2 produced (z-score)")

library(visreg)
visreg(O1, "non_crystal","depth", xlab="vari", ylab="CO2 produced (z-score)")

library(visreg)
visreg(O1, "S_16S", xlab="vari", ylab="CO2 produced (z-score)")

library(visreg)
#visreg2d(O1, "non_crystal","Delta_temp", xlab="vari", ylab="CO2 produced (z-score)",  plot.type="rgl")

b <- getViz(O1)
qq(b, method = "simul1", a.qqpoi = list("shape" = 1), a.ablin = list("linetype" = 2))

```

```{r}
#partial residual plot, MAT

Rf<-O1$resid[,1] #full model residuals

MAT.c<-coef(mod_try)$pro_bio1[1] #predictor coefficient

MAT.pr<-Rf+MAT.c*frc_data_test$pro_bio1 #Residuals + pred coef * predictor value

 

plot(MAT.pr~frc_data_test$pro_bio1) #plot partial residual vs predictor value

abline(lm(MAT.c*frc_data_test$pro_bio1~frc_data_test$pro_bio1), col="red") #"component", where fitted line would be

#lines(frc_data_test$pro_bio1,fitted(lm(MAT.c*frc_data_test$pro_bio1~frc_data_test$pro_bio1)), col="red") #same as above

abline(lm(MAT.pr~frc_data_test$pro_bio1), col="green") #residual line
```

```{r}
Lyon_adj_mean$depth <- factor(Lyon_adj_mean$depth)
library(mgcv)
library(mgcViz)
library(MuMIn)

O1 =  gam(log(co2) ~ s(Delta_temp, k =3, by =depth)+ s(N, k=3, by =depth)+ s(vwc, k=3, by =depth)  + s(non_crystal, k=3, by =depth)  + s(id, bs = "re")+ 1, data = Lyon_adj_mean, na.action = "na.fail", method ="REML")

O2 =  gam(log(co2) ~ s(Delta_temp, k =3, by =depth)+ s(S_16S, k=3, by =depth)+ s(vwc, k=3, by =depth) + s(non_crystal, k=3, by =depth)  + s(id, bs = "re")+ 1,  data = Lyon_adj_mean, na.action = "na.fail", method ="REML")

O3 =  gam(log(co2) ~ s(Delta_temp, k =3, by =depth)+ s(S_16S, k=3, by =depth)+ s(vwc, k=3, by =depth)+ s(Fe_h_Fe_d, k=3, by =depth), data = Lyon_adj_mean, na.action = "na.fail", method ="REML")

O2 =  gam(log(co2) ~ s(Delta_temp, k =3, by =depth)+ s(vwc, k=3, by =depth) + s(non_crystal, k=3, by =depth)  + s(id, bs = "re")+ 1, , data = Lyon_adj_mean, na.action = "na.fail", method ="REML")

AICc(O1,O2,O3, O4)
```
```{r}
x_new <- seq(0, max(Lyon_adj_mean$Delta_temp), length.out = 100)
y_pred <- predict(O4, data.frame(x = x_new))
