---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#set working location where files are stored
setwd("C:\\Users\\14014\\Desktop\\UH_Soil_Warming\\Manuscript")

#location IDS
heaters <- read.csv(file="temp_heaters.csv", skip=1, header=FALSE, stringsAsFactors = F) 
names(heaters) <- c("Ambient", "Heated", "year", "month", "day")

#combine year month day
heaters$date <- with(heaters,
paste(year, month, day, sep = "-"))
#head(Lyon_df$date, 4) # show first four elements
## [1] "1990-1-1" "1990-1-2" "1990-1-3" "1990-1-4"

#create date object 
heaters$date <- as.Date(heaters$date)
#class(Lyon_df$date)
```

```{r}
library(ggplot2)
library(ggplot2)
p <- ggplot() + 
  geom_line(data = heaters, aes(x = date, y = Ambient), color = "blue") +
  geom_line(data = heaters, aes(x = date, y = Heated), color = "red") +
  xlab('Date') +
  ylab('Soil temperature (°C)')

p + theme_classic(base_size = 14)
                  #)+scale_x_date(breaks = breaks_pretty(10))+
  #theme(axis.text.x = element_text(angle=45, hjust = 1))

```

